### ISSUE TITLE
[Question] Why is `defun` non-existent in the `eval()` context?

### ISSUE THREAD

**Issue by alexmozaidze** [ytakano/blisp#2]
I'm curious, is there a reason behind it?

**Comment by ytakano** [comment]
Because BLips is designed as a DSL for remote procedure call (RPC).
A client can only call functions provided by the server, and the RPC will be performed by `eval()`.

Of course, `eval()` accepting `defun` is possible, but defining IO functions in `eval()` must be prohibited because of some security reasons.

I think `eval()` accepting only expressions is sufficient for RPC.

Thank you!

**Comment by alexmozaidze** [comment]
It would be great if you added a setting to allow defining non-IO functions in `eval()`. I'm making scripting for my game and since those scripts can sometimes be really big and repetitive, having an ability to define a custom function is nice.
